# .pre-commit-config.yaml
repos:
-   repo: local
    hooks:
    -   id: Flake8
        name: flake8
        entry: flake8 flaskr tests noxfile.py
        language: system
        types: [python]
        verbose: true
