config:
    DATABASE_NAME: ENC[AES256_GCM,data:aQVyfGGqXxyh,iv:SNO2nMv4VhMYGKj3cRxGu1bSqsR2H1ontD2GFBtchhc=,tag:dydcsIUUAi+Tatk/5gM81g==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:uZgnordFbLs=,iv:5PHamAgJtiWnRFBgr2k5vyNu1wvaEXoi08psXctvjvY=,tag:IGfX6HflZyP4U5AEwL7eqA==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:Z3V64A==,iv:B08oLOy1JodthRSHY9YOPU3uiu0DPyWohzqYBYXnJws=,tag:zk7vosUQJlTIlXStwNpJOQ==,type:int]
    DATABASE_USER: ENC[AES256_GCM,data:0azL5yoD2Ilj,iv:Xa71EH7E1p1knB7g4Q5UUm79M6YYpal/Bq68pEzqLmE=,tag:Lr0WajtyU3VDl1LTmXZy/A==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:DfVTjh5SO3DG,iv:ygCQgjwAuuzKmyTvJxdPhhc4LKGA91LgE2YL80shq4s=,tag:LHqGDvi9lwMtr+5QiCpjsQ==,type:str]
    JUMPCLOUD_BASE_URL: ENC[AES256_GCM,data:cgGLOeW+1ThPvE5dk8jWBIny7iEtveTfa+JqEfDQDqTC,iv:uNUqU0hr+pocrfwIgdGkMOd9wicZuoLpV/2rZgStPwU=,tag:/u0tJ65WvKKfjlDaCzbgDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-10-31T20:53:25Z'
    mac: ENC[AES256_GCM,data:uzV8xbURpL3ssTN1xDMCaIamOS+RGlrUWHRnW9dnUNVnp8S9YAOPYmCx1/kJqUH3CKHs8rvjagYwtPgYPRZixJ6xcfaybeyO5R0Q+km6alsWryLiFafajrFi770OmNCCsX2Ioqs1EEMbuJt3+uxhskes4PSkSUbsBs7AIaeEE5Y=,iv:ctFOWX37l5CElSAsmshqZenJvUoMK7knO+DA+zWKAvU=,tag:ph1ZGfX24XG7B5SgdTDtvw==,type:str]
    pgp:
    -   created_at: '2020-10-31T20:53:24Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA18ZLS9BjZuGAQv+KkKAc3ySUqDdQx9JN5dc3zDBhr97E37ILGX/KyyByB1N
            0tBIEjlXqfP1rbdyxEMYBYVs1keSN1PWcxF/GfBT1pCgUHWPP2xCsxdXBWP4RHyt
            cM557HRKd/9+Z/j0E78RMIs/Fw6T/II6NvRT3ElIXcJ5Wve/Vzyb8nzvrFeB2KaE
            87Vq991Hw8D+K6Tqp1hSNXS4cJq0IdkZ9N6sYOK3BUNAELPfNqj9UjZnweP67BhL
            IiEGaGcSKpspdesUfk5DLB6bsIiueGRLUgBWcMBuRacKZD7niSRUSbTQKLBf1KtS
            86z+4FBT/f3waXPQ1B5EIdxJuwnBG7GIn2eObuTVjhZS7nyRffS5Hn31GmthuH39
            3zxxpWbG9j9r4choe8WmGecW6DC8T1ArogObzXrYhgYfEZiavo0w+UdVnA0Uzp9o
            QnJkR2P0Cqo4zqppIxk+foHQwvwAgDL5sE9pT291OKL2NAP/NaPfv/sKTCOmAut5
            C5irn2XVx7auLCi4e4GX0lwBqCU0OCrQl+GX74k64uGB0TTglxaCaKgW+FrLi0Ip
            W21k5JxYltKdtki0YH7/u8JIQ+Jsk5nhAgl1Wnc3GGTnp+1klZRJCxvjXU6RCXs0
            2qUmun8VHAWtiHB97w==
            =euAj
            -----END PGP MESSAGE-----
        fp: 6AA9FBF2F6A6416FC1230D17ECB2FBC15E323508
    unencrypted_suffix: _unencrypted
    version: 3.5.0
